-- Content submission intake and admin moderation foundation.
-- Run after 001_content.sql, 002_content_lifecycle.sql and 003_public_published_policy.sql.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

drop policy if exists "Admins can read their own admin record" on public.admin_users;
create policy "Admins can read their own admin record"
  on public.admin_users
  for select
  to authenticated
  using (user_id = auth.uid());

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

create table if not exists public.content_submissions (
  id bigint generated by default as identity primary key,
  submitted_by uuid references auth.users(id) on delete set null,
  type text not null check (type in ('place', 'event', 'business', 'community')),
  title text not null check (char_length(trim(title)) between 1 and 160),
  category text check (category is null or char_length(trim(category)) <= 80),
  description text not null check (char_length(trim(description)) between 1 and 1000),
  details text check (details is null or char_length(details) <= 5000),
  date_text text check (date_text is null or char_length(trim(date_text)) <= 120),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists content_submissions_status_created_idx
  on public.content_submissions (status, created_at desc);

create index if not exists content_submissions_type_idx
  on public.content_submissions (type);

create or replace function public.set_content_submissions_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists content_submissions_set_updated_at on public.content_submissions;
create trigger content_submissions_set_updated_at
before update on public.content_submissions
for each row
execute function public.set_content_submissions_updated_at();

alter table public.content_submissions enable row level security;

drop policy if exists "Public can submit pending content" on public.content_submissions;
create policy "Public can submit pending content"
  on public.content_submissions
  for insert
  to anon, authenticated
  with check (
    status = 'pending'
    and (submitted_by is null or submitted_by = auth.uid())
  );

drop policy if exists "Admins can read submissions" on public.content_submissions;
create policy "Admins can read submissions"
  on public.content_submissions
  for select
  to authenticated
  using (public.is_admin());

drop policy if exists "Admins can moderate submissions" on public.content_submissions;
create policy "Admins can moderate submissions"
  on public.content_submissions
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

revoke all on public.content_submissions from anon, authenticated;
grant insert on public.content_submissions to anon, authenticated;
grant select, update on public.content_submissions to authenticated;

drop policy if exists "Admins can manage content" on public.content_items;
create policy "Admins can manage content"
  on public.content_items
  for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

grant insert, update, delete on public.content_items to authenticated;
